name: PR Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  pr-workflow:
    name: PR Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run unit tests
        run: |
          python3 tests.py
      - name: Lint the code
        run: |
          pylint --rcfile pylintrc .
      - name: Run Sonar scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      - name: Run Sonar Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      - name: Show result
        run: |
          echo "Sonar Quality Gate status: ${{ steps.sonarqube-quality-gate-check.outputs.status }}"
          echo "Sonar Quality Gate message: ${{ steps.sonarqube-quality-gate-check.outputs.message }}"
          echo "Sonar Quality Gate passed: ${{ steps.sonarqube-quality-gate-check.outputs.passed }}"
          echo "Sonar Quality Gate conditions: ${{ steps.sonarqube-quality-gate-check.outputs.conditions }}"
          echo "Sonar Quality Gate error: ${{ steps.sonarqube-quality-gate-check.outputs.error }}"
          echo "Sonar Quality Gate details: ${{ steps.sonarqube-quality-gate-check.outputs.details }}"
