name: PR Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  pr-workflow:
    name: PR Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run unit tests
        run: |
          python3 tests.py
      - name: Lint the code
        run: |
          pylint --rcfile pylintrc .
      - name: Run Sonar scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
